#!/bin/sh
source="${HOME}/Downloads"
target="${HOME}/Library/Mobile\ Documents/com~apple~CloudDocs"

for x in ${source}/*.torrent
do
	if test -f "${x}"; then
		mv "${x}" "${target}"/"$(basename "${x}")"
	fi
done
